title: "LMMS Producers"
author: "LMMS Producers"
description: "The home of the LMMSians"
# subheading:  "The home of the LMMSians"
more: "read more"
url: "http://bado.so"
baseurl: "/lmms" # comment out if in root directory

comments:
#    disqus: "niklasbuschmann"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: 'https://github.com/badosu/lmms-producers'
  - rss: '/feed.xml'
#  - soundcloud: "https://twitter.com/me/"
#  - google-plus: "https://plus.google.com/+me"
#  - reddit: "https://www.reddit.com/user/me/"
#  - youtube: "https://www.youtube.com/user/me"
#  - steam: "http://steamcommunity.com/id/me/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
